const movies = [
	{
		id: 1,
		Title: "The Shawshank Redemption",
		Year: "2001",
		Genre: "Thriller, Adventure",
		Poster: "https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
		imdbRating: "6.8",
		Director: "Kenneth Branagh",
		Actors: "Chris Evans, Mark Ruffalo, Chris Hemsworth",
	},
	{
		id: 2,
		Title: "The Godfather",
		Year: "2002",
		Genre: "Drama, Action",
		Poster: "https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
		imdbRating: "5.9",
		Director: "Taika Waititi",
		Actors: "Chris Evans, Robert Downey Jr., Mark Ruffalo",
	},
	{
		id: 3,
		Title: "The Dark Knight",
		Year: "2003",
		Genre: "Comedy, Drama",
		Poster: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg",
		imdbRating: "7.5",
		Director: "Joe Russo",
		Actors: "Chris Hemsworth, Chris Evans, Mark Ruffalo",
	},
	{
		id: 4,
		Title: "Pulp Fiction",
		Year: "2004",
		Genre: "Drama, Fantasy",
		Poster: "https://upload.wikimedia.org/wikipedia/en/3/3b/Pulp_Fiction_%281994%29_poster.jpg",
		imdbRating: "5.7",
		Director: "Joss Whedon",
		Actors: "Robert Downey Jr., Chris Evans, Scarlett Johansson",
	},
	{
		id: 5,
		Title: "Forrest Gump",
		Year: "2005",
		Genre: "Drama, Sci-Fi",
		Poster: "https://m.media-amazon.com/images/M/MV5BNDYwNzVjMTItZmU5YS00YjQ5LTljYjgtMjY2NDVmYWMyNWFmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
		imdbRating: "7.5",
		Director: "Kenneth Branagh",
		Actors: "Mark Ruffalo, Robert Downey Jr., Chris Evans",
	},
	{
		id: 6,
		Title: "Inception",
		Year: "2006",
		Genre: "Fantasy, Sci-Fi",
		Poster: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_QL75_UX190_CR0,0,190,281_.jpg",
		imdbRating: "5.2",
		Director: "Joe Russo",
		Actors: "Chris Evans, Mark Ruffalo, Robert Downey Jr.",
	},
	{
		id: 7,
		Title: "Fight Club",
		Year: "2007",
		Genre: "Drama, Sci-Fi",
		Poster: "https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
		imdbRating: "6.7",
		Director: "Taika Waititi",
		Actors: "Robert Downey Jr., Chris Evans, Scarlett Johansson",
	},
	{
		id: 8,
		Title: "The Matrix",
		Year: "2008",
		Genre: "Adventure, Thriller",
		Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfSjSWOCaw5dnDL2GT1zFd9RMCgUGw5Q2Cfg&s",
		imdbRating: "5.7",
		Director: "Kenneth Branagh",
		Actors: "Mark Ruffalo, Chris Hemsworth, Robert Downey Jr.",
	},
	{
		id: 9,
		Title: "The Lord of the Rings: The Return of the King",
		Year: "2009",
		Genre: "Adventure, Sci-Fi",
		Poster: "https://m.media-amazon.com/images/M/MV5BMTZkMjBjNWMtZGI5OC00MGU0LTk4ZTItODg2NWM3NTVmNWQ4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
		imdbRating: "5.7",
		Director: "Jon Favreau",
		Actors: "Chris Hemsworth, Robert Downey Jr., Chris Evans",
	},
	{
		id: 10,
		Title: "Interstellar",
		Year: "2010",
		Genre: "Sci-Fi, Action",
		Poster: "https://m.media-amazon.com/images/S/pv-target-images/8f7cd92b0bb7ce2b0eae88ee539a52f23199c67131a8c15f0ecbc0d4e7194062.jpg",
		imdbRating: "5.1",
		Director: "Kenneth Branagh",
		Actors: "Scarlett Johansson, Mark Ruffalo, Chris Hemsworth",
	},
	{
		id: 11,
		Title: "The Green Mile",
		Year: "2011",
		Genre: "Action, Sci-Fi",
		Poster: "https://upload.wikimedia.org/wikipedia/th/4/43/TheGreenMile-Poster.jpg",
		imdbRating: "7.1",
		Director: "Joss Whedon",
		Actors: "Mark Ruffalo, Chris Evans, Robert Downey Jr.",
	},
	{
		id: 12,
		Title: "Gladiator",
		Year: "2012",
		Genre: "Adventure, Comedy",
		Poster: "https://example.com/poster12.jpg",
		imdbRating: "5.7",
		Director: "Joe Russo",
		Actors: "Chris Hemsworth, Mark Ruffalo, Robert Downey Jr.",
	},
	{
		id: 13,
		Title: "The Lion King",
		Year: "2013",
		Genre: "Thriller, Sci-Fi",
		Poster: "https://example.com/poster13.jpg",
		imdbRating: "8.0",
		Director: "Taika Waititi",
		Actors: "Mark Ruffalo, Scarlett Johansson, Chris Evans",
	},
	{
		id: 14,
		Title: "The Prestige",
		Year: "2014",
		Genre: "Thriller, Sci-Fi",
		Poster: "https://example.com/poster14.jpg",
		imdbRating: "8.4",
		Director: "Jon Favreau",
		Actors: "Robert Downey Jr., Chris Hemsworth, Chris Evans",
	},
	{
		id: 15,
		Title: "The Departed",
		Year: "2015",
		Genre: "Thriller, Sci-Fi",
		Poster: "https://example.com/poster15.jpg",
		imdbRating: "8.6",
		Director: "Joe Russo",
		Actors: "Robert Downey Jr., Chris Hemsworth, Scarlett Johansson",
	},
	{
		id: 16,
		Title: "The Avengers",
		Year: "2016",
		Genre: "Thriller, Sci-Fi",
		Poster: "https://example.com/poster16.jpg",
		imdbRating: "7.6",
		Director: "Joss Whedon",
		Actors: "Mark Ruffalo, Robert Downey Jr., Chris Evans",
	},
	{
		id: 17,
		Title: "Avengers: Endgame",
		Year: "2017",
		Genre: "Thriller, Comedy",
		Poster: "https://example.com/poster17.jpg",
		imdbRating: "7.1",
		Director: "Kenneth Branagh",
		Actors: "Mark Ruffalo, Scarlett Johansson, Chris Hemsworth",
	},
	{
		id: 18,
		Title: "Avengers: Infinity War",
		Year: "2018",
		Genre: "Adventure, Sci-Fi",
		Poster: "https://example.com/poster18.jpg",
		imdbRating: "8.6",
		Director: "Jon Favreau",
		Actors: "Chris Evans, Chris Hemsworth, Mark Ruffalo",
	},
	{
		id: 19,
		Title: "Iron Man",
		Year: "2019",
		Genre: "Fantasy, Sci-Fi",
		Poster: "https://example.com/poster19.jpg",
		imdbRating: "6.8",
		Director: "Taika Waititi",
		Actors: "Chris Evans, Chris Hemsworth, Scarlett Johansson",
	},
	{
		id: 20,
		Title: "Captain America: The Winter Soldier",
		Year: "2000",
		Genre: "Comedy, Drama",
		Poster: "https://example.com/poster20.jpg",
		imdbRating: "7.1",
		Director: "Taika Waititi",
		Actors: "Chris Hemsworth, Scarlett Johansson, Mark Ruffalo",
	},
	{
		id: 21,
		Title: "Thor: Ragnarok",
		Year: "2001",
		Genre: "Action, Drama",
		Poster: "https://example.com/poster21.jpg",
		imdbRating: "8.7",
		Director: "Joe Russo",
		Actors: "Chris Hemsworth, Robert Downey Jr., Scarlett Johansson",
	},
	{
		id: 22,
		Title: "Guardians of the Galaxy",
		Year: "2002",
		Genre: "Adventure, Fantasy",
		Poster: "https://example.com/poster22.jpg",
		imdbRating: "7.0",
		Director: "Joe Russo",
		Actors: "Scarlett Johansson, Robert Downey Jr., Chris Evans",
	},
	{
		id: 23,
		Title: "Doctor Strange",
		Year: "2003",
		Genre: "Fantasy, Thriller",
		Poster: "https://example.com/poster23.jpg",
		imdbRating: "7.4",
		Director: "Jon Favreau",
		Actors: "Chris Hemsworth, Chris Evans, Robert Downey Jr.",
	},
	{
		id: 24,
		Title: "Black Panther",
		Year: "2004",
		Genre: "Thriller, Comedy",
		Poster: "https://example.com/poster24.jpg",
		imdbRating: "7.9",
		Director: "Joss Whedon",
		Actors: "Chris Hemsworth, Scarlett Johansson, Mark Ruffalo",
	},
	{
		id: 25,
		Title: "Spider-Man: No Way Home",
		Year: "2005",
		Genre: "Comedy, Action",
		Poster: "https://example.com/poster25.jpg",
		imdbRating: "8.3",
		Director: "Joss Whedon",
		Actors: "Robert Downey Jr., Chris Hemsworth, Mark Ruffalo",
	},
	{
		id: 26,
		Title: "Joker",
		Year: "2006",
		Genre: "Drama, Fantasy",
		Poster: "https://example.com/poster26.jpg",
		imdbRating: "5.0",
		Director: "Jon Favreau",
		Actors: "Mark Ruffalo, Chris Hemsworth, Chris Evans",
	},
	{
		id: 27,
		Title: "Django Unchained",
		Year: "2007",
		Genre: "Thriller, Sci-Fi",
		Poster: "https://example.com/poster27.jpg",
		imdbRating: "7.9",
		Director: "Jon Favreau",
		Actors: "Mark Ruffalo, Chris Evans, Scarlett Johansson",
	},
	{
		id: 28,
		Title: "The Wolf of Wall Street",
		Year: "2008",
		Genre: "Action, Fantasy",
		Poster: "https://example.com/poster28.jpg",
		imdbRating: "6.8",
		Director: "Joss Whedon",
		Actors: "Robert Downey Jr., Chris Evans, Mark Ruffalo",
	},
	{
		id: 29,
		Title: "Shutter Island",
		Year: "2009",
		Genre: "Action, Fantasy",
		Poster: "https://example.com/poster29.jpg",
		imdbRating: "7.1",
		Director: "Anthony Russo",
		Actors: "Scarlett Johansson, Mark Ruffalo, Chris Hemsworth",
	},
	{
		id: 30,
		Title: "Whiplash",
		Year: "2010",
		Genre: "Adventure, Fantasy",
		Poster: "https://example.com/poster30.jpg",
		imdbRating: "6.3",
		Director: "Joss Whedon",
		Actors: "Mark Ruffalo, Robert Downey Jr., Chris Evans",
	},
];

module.exports = movies;
