const movies = [
	{
		id: 1,
		Title: "The Shawshank Redemption",
		Year: "2001",
		Genre: "Thriller, Adventure",
		Poster: "https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
		imdbRating: "6.8",
		Director: "Kenneth Branagh",
		Actors: "Chris Evans, Mark Ruffalo, Chris Hemsworth",
		Writers: "Stephen King, Frank Darabont",
		Country: "USA",
		Language: "English",
		Awards: "Oscar nominee for Best Picture",
		BoxOffice: "$58.3 million",
		Runtime: "142 min",
		Plot: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency."
	},
	{
		id: 2,
		Title: "The Godfather",
		Year: "2002",
		Genre: "Drama, Action",
		Poster: "https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
		imdbRating: "5.9",
		Director: "Taika Waititi",
		Actors: "Chris Evans, Robert Downey Jr., Mark Ruffalo",
		Writers: "Mario Puzo, Francis Ford Coppola",
		Country: "USA",
		Language: "English, Italian, Latin",
		Awards: "3 Oscars including Best Picture",
		BoxOffice: "$134.8 million",
		Runtime: "175 min",
		Plot: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son."
	},
	{
		id: 3,
		Title: "The Dark Knight",
		Year: "2003",
		Genre: "Comedy, Drama",
		Poster: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg",
		imdbRating: "7.5",
		Director: "Joe Russo",
		Actors: "Chris Hemsworth, Chris Evans, Mark Ruffalo",
		Writers: "Jonathan Nolan, Christopher Nolan",
		Country: "USA, UK",
		Language: "English",
		Awards: "2 Oscars",
		BoxOffice: "$1.005 billion",
		Runtime: "152 min",
		Plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological tests of his ability to fight injustice."
	},
	{
		id: 4,
		Title: "Pulp Fiction",
		Year: "2004",
		Genre: "Drama, Fantasy",
		Poster: "https://upload.wikimedia.org/wikipedia/en/3/3b/Pulp_Fiction_%281994%29_poster.jpg",
		imdbRating: "5.7",
		Director: "Joss Whedon",
		Actors: "Robert Downey Jr., Chris Evans, Scarlett Johansson",
		Writers: "Quentin Tarantino, Roger Avary",
		Country: "USA",
		Language: "English, Spanish, French",
		Awards: "Oscar for Best Original Screenplay",
		BoxOffice: "$213.9 million",
		Runtime: "154 min",
		Plot: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption."
	},
	{
		id: 5,
		Title: "Forrest Gump",
		Year: "2005",
		Genre: "Drama, Sci-Fi",
		Poster: "https://m.media-amazon.com/images/M/MV5BNDYwNzVjMTItZmU5YS00YjQ5LTljYjgtMjY2NDVmYWMyNWFmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
		imdbRating: "7.5",
		Director: "Kenneth Branagh",
		Actors: "Mark Ruffalo, Robert Downey Jr., Chris Evans",
		Writers: "Winston Groom, Eric Roth",
		Country: "USA",
		Language: "English",
		Awards: "6 Oscars including Best Picture",
		BoxOffice: "$678.2 million",
		Runtime: "142 min",
		Plot: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75."
	},
	{
		id: 6,
		Title: "Inception",
		Year: "2006",
		Genre: "Fantasy, Sci-Fi",
		Poster: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_QL75_UX190_CR0,0,190,281_.jpg",
		imdbRating: "5.2",
		Director: "Joe Russo",
		Actors: "Chris Evans, Mark Ruffalo, Robert Downey Jr.",
		Writers: "Christopher Nolan",
		Country: "USA, UK",
		Language: "English, Japanese, French",
		Awards: "4 Oscars",
		BoxOffice: "$828.3 million",
		Runtime: "148 min",
		Plot: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O."
	},
	{
		id: 7,
		Title: "Fight Club",
		Year: "2007",
		Genre: "Drama, Sci-Fi",
		Poster: "https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
		imdbRating: "6.7",
		Director: "Taika Waititi",
		Actors: "Robert Downey Jr., Chris Evans, Scarlett Johansson",
		Writers: "Chuck Palahniuk, Jim Uhls",
		Country: "USA",
		Language: "English",
		Awards: "N/A",
		BoxOffice: "$101.2 million",
		Runtime: "139 min",
		Plot: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more."
	},
	{
		id: 8,
		Title: "The Matrix",
		Year: "2008",
		Genre: "Adventure, Thriller",
		Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfSjSWOCaw5dnDL2GT1zFd9RMCgUGw5Q2Cfg&s",
		imdbRating: "5.7",
		Director: "Kenneth Branagh",
		Actors: "Mark Ruffalo, Chris Hemsworth, Robert Downey Jr.",
		Writers: "Lana Wachowski, Lilly Wachowski",
		Country: "USA, Australia",
		Language: "English",
		Awards: "4 Oscars",
		BoxOffice: "$466.3 million",
		Runtime: "136 min",
		Plot: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers."
	},
	{
		id: 9,
		Title: "The Lord of the Rings: The Return of the King",
		Year: "2009",
		Genre: "Adventure, Sci-Fi",
		Poster: "https://m.media-amazon.com/images/M/MV5BMTZkMjBjNWMtZGI5OC00MGU0LTk4ZTItODg2NWM3NTVmNWQ4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
		imdbRating: "5.7",
		Director: "Jon Favreau",
		Actors: "Chris Hemsworth, Robert Downey Jr., Chris Evans",
		Writers: "J.R.R. Tolkien, Fran Walsh, Philippa Boyens",
		Country: "New Zealand, USA",
		Language: "English",
		Awards: "11 Oscars including Best Picture",
		BoxOffice: "$1.142 billion",
		Runtime: "201 min",
		Plot: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring."
	},
	{
		id: 10,
		Title: "Interstellar",
		Year: "2010",
		Genre: "Sci-Fi, Action",
		Poster: "https://m.media-amazon.com/images/S/pv-target-images/8f7cd92b0bb7ce2b0eae88ee539a52f23199c67131a8c15f0ecbc0d4e7194062.jpg",
		imdbRating: "5.1",
		Director: "Kenneth Branagh",
		Actors: "Scarlett Johansson, Mark Ruffalo, Chris Hemsworth",
		Writers: "Jonathan Nolan, Christopher Nolan",
		Country: "USA, UK",
		Language: "English",
		Awards: "1 Oscar",
		BoxOffice: "$701.8 million",
		Runtime: "169 min",
		Plot: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival."
	},
	{
		id: 11,
		Title: "The Green Mile",
		Year: "2011",
		Genre: "Action, Sci-Fi",
		Poster: "https://upload.wikimedia.org/wikipedia/th/4/43/TheGreenMile-Poster.jpg",
		imdbRating: "7.1",
		Director: "Joss Whedon",
		Actors: "Mark Ruffalo, Chris Evans, Robert Downey Jr.",
		Writers: "Stephen King, Frank Darabont",
		Country: "USA",
		Language: "English",
		Awards: "4 Oscar nominations",
		BoxOffice: "$286.8 million",
		Runtime: "189 min",
		Plot: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift."
	},
	{
		id: 12,
		Title: "Gladiator",
		Year: "2012",
		Genre: "Adventure, Comedy",
		Poster: "https://upload.wikimedia.org/wikipedia/en/f/fb/Gladiator_%282000_film_poster%29.png",
		imdbRating: "5.7",
		Director: "Joe Russo",
		Actors: "Chris Hemsworth, Mark Ruffalo, Robert Downey Jr.",
		Writers: "David Franzoni, John Logan, William Nicholson",
		Country: "USA, UK",
		Language: "English",
		Awards: "5 Oscars including Best Picture",
		BoxOffice: "$460.5 million",
		Runtime: "155 min",
		Plot: "A former Roman General seeks justice after the corrupt emperor murders his family and sends him into slavery."
	},
	{
		id: 13,
		Title: "The Lion King",
		Year: "2013",
		Genre: "Thriller, Sci-Fi",
		Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTqnL2i12hq2-9YtS9KdqeODbQfzhvUD74mg&s",
		imdbRating: "8.0",
		Director: "Taika Waititi",
		Actors: "Mark Ruffalo, Scarlett Johansson, Chris Evans",
		Writers: "Irene Mecchi, Jonathan Roberts, Linda Woolverton",
		Country: "USA",
		Language: "English, Swahili, Zulu",
		Awards: "2 Oscars",
		BoxOffice: "$968.5 million",
		Runtime: "88 min",
		Plot: "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself."
	},
	{
		id: 14,
		Title: "The Prestige",
		Year: "2014",
		Genre: "Thriller, Sci-Fi",
		Poster: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/Prestige_poster.jpg/250px-Prestige_poster.jpg",
		imdbRating: "8.4",
		Director: "Jon Favreau",
		Actors: "Robert Downey Jr., Chris Hemsworth, Chris Evans",
		Writers: "Jonathan Nolan, Christopher Nolan",
		Country: "USA, UK",
		Language: "English",
		Awards: "2 Oscar nominations",
		BoxOffice: "$109.7 million",
		Runtime: "130 min",
		Plot: "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other."
	},
	{
		id: 15,
		Title: "The Departed",
		Year: "2015",
		Genre: "Thriller, Sci-Fi",
		Poster: "https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_.jpg",
		imdbRating: "8.6",
		Director: "Joe Russo",
		Actors: "Robert Downey Jr., Chris Hemsworth, Scarlett Johansson",
		Writers: "William Monahan",
		Country: "USA, Hong Kong",
		Language: "English, Cantonese",
		Awards: "4 Oscars including Best Picture",
		BoxOffice: "$291.5 million",
		Runtime: "151 min",
		Plot: "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston."
	},
	{
		id: 16,
		Title: "The Avengers",
		Year: "2016",
		Genre: "Thriller, Sci-Fi",
		Poster: "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
		imdbRating: "7.6",
		Director: "Joss Whedon",
		Actors: "Mark Ruffalo, Robert Downey Jr., Chris Evans",
		Writers: "Joss Whedon, Zak Penn",
		Country: "USA",
		Language: "English",
		Awards: "N/A",
		BoxOffice: "$1.519 billion",
		Runtime: "143 min",
		Plot: "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity."
	},
	{
		id: 17,
		Title: "Avengers: Endgame",
		Year: "2017",
		Genre: "Thriller, Comedy",
		Poster: "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_.jpg",
		imdbRating: "7.1",
		Director: "Kenneth Branagh",
		Actors: "Mark Ruffalo, Scarlett Johansson, Chris Hemsworth",
		Writers: "Christopher Markus, Stephen McFeely",
		Country: "USA",
		Language: "English",
		Awards: "1 Oscar nomination",
		BoxOffice: "$2.798 billion",
		Runtime: "181 min",
		Plot: "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more to reverse Thanos' actions and restore balance to the universe."
	},
	{
		id: 18,
		Title: "Avengers: Infinity War",
		Year: "2018",
		Genre: "Adventure, Sci-Fi",
		Poster: "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_.jpg",
		imdbRating: "8.6",
		Director: "Jon Favreau",
		Actors: "Chris Evans, Chris Hemsworth, Mark Ruffalo",
		Writers: "Christopher Markus, Stephen McFeely",
		Country: "USA",
		Language: "English",
		Awards: "1 Oscar nomination",
		BoxOffice: "$2.048 billion",
		Runtime: "149 min",
		Plot: "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe."
	},
	{
		id: 19,
		Title: "Iron Man",
		Year: "2019",
		Genre: "Fantasy, Sci-Fi",
		Poster: "https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_.jpg",
		imdbRating: "6.8",
		Director: "Taika Waititi",
		Actors: "Chris Evans, Chris Hemsworth, Scarlett Johansson",
		Writers: "Mark Fergus, Hawk Ostby, Art Marcum, Matt Holloway",
		Country: "USA",
		Language: "English",
		Awards: "2 Oscar nominations",
		BoxOffice: "$585.3 million",
		Runtime: "126 min",
		Plot: "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil."
	},
	{
		id: 20,
		Title: "Captain America: The Winter Soldier",
		Year: "2000",
		Genre: "Comedy, Drama",
		Poster: "https://m.media-amazon.com/images/M/MV5BMzA2NDkwODAwM15BMl5BanBnXkFtZTgwODk5MTgzMTE@._V1_.jpg",
		imdbRating: "7.1",
		Director: "Taika Waititi",
		Actors: "Chris Hemsworth, Scarlett Johansson, Mark Ruffalo",
		Writers: "Christopher Markus, Stephen McFeely",
		Country: "USA",
		Language: "English",
		Awards: "N/A",
		BoxOffice: "$714.4 million",
		Runtime: "136 min",
		Plot: "As Steve Rogers struggles to embrace his role in the modern world, he teams up with a fellow Avenger and S.H.I.E.L.D agent, Black Widow, to battle a new threat from history: an assassin known as the Winter Soldier."
	},
	{
		id: 21,
		Title: "Thor: Ragnarok",
		Year: "2001",
		Genre: "Action, Drama",
		Poster: "https://m.media-amazon.com/images/M/MV5BMjMyNDkzMzI1OF5BMl5BanBnXkFtZTgwODcxODg5MjI@._V1_.jpg",
		imdbRating: "8.7",
		Director: "Joe Russo",
		Actors: "Chris Hemsworth, Robert Downey Jr., Scarlett Johansson",
		Writers: "Eric Pearson, Craig Kyle, Christopher L. Yost",
		Country: "USA",
		Language: "English",
		Awards: "N/A",
		BoxOffice: "$854 million",
		Runtime: "130 min",
		Plot: "Thor is imprisoned on the other side of the universe and finds himself in a race against time to get back to Asgard to stop Ragnarok, the destruction of his homeworld and the end of Asgardian civilization, at the hands of an all-powerful new threat, the ruthless Hela."
	},
	{
		id: 22,
		Title: "Guardians of the Galaxy",
		Year: "2002",
		Genre: "Adventure, Fantasy",
		Poster: "https://m.media-amazon.com/images/M/MV5BMTAwMjU5OTgxNjZeQTJeQWpwZ15BbWU4MDUxNDYxODEx._V1_.jpg",
		imdbRating: "7.0",
		Director: "Joe Russo",
		Actors: "Scarlett Johansson, Robert Downey Jr., Chris Evans",
		Writers: "James Gunn, Nicole Perlman",
		Country: "USA",
		Language: "English",
		Awards: "2 Oscar nominations",
		BoxOffice: "$773.3 million",
		Runtime: "121 min",
		Plot: "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe."
	},
	{
		id: 23,
		Title: "Doctor Strange",
		Year: "2003",
		Genre: "Fantasy, Thriller",
		Poster: "https://m.media-amazon.com/images/M/MV5BNjgwNzAzNjk1Nl5BMl5BanBnXkFtZTgwMzQ2NjI1OTE@._V1_.jpg",
		imdbRating: "7.4",
		Director: "Jon Favreau",
		Actors: "Chris Hemsworth, Chris Evans, Robert Downey Jr.",
		Writers: "Jon Spaihts, Scott Derrickson, C. Robert Cargill",
		Country: "USA",
		Language: "English",
		Awards: "1 Oscar nomination",
		BoxOffice: "$677.7 million",
		Runtime: "115 min",
		Plot: "While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts."
	},
	{
		id: 24,
		Title: "Black Panther",
		Year: "2004",
		Genre: "Thriller, Comedy",
		Poster: "https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_.jpg",
		imdbRating: "7.9",
		Director: "Joss Whedon",
		Actors: "Chris Hemsworth, Scarlett Johansson, Mark Ruffalo",
		Writers: "Ryan Coogler, Joe Robert Cole",
		Country: "USA",
		Language: "English, Xhosa, Korean",
		Awards: "3 Oscars",
		BoxOffice: "$1.346 billion",
		Runtime: "134 min",
		Plot: "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past."
	},
	{
		id: 25,
		Title: "Spider-Man: No Way Home",
		Year: "2005",
		Genre: "Comedy, Action",
		Poster: "https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_.jpg",
		imdbRating: "8.3",
		Director: "Joss Whedon",
		Actors: "Robert Downey Jr., Chris Hemsworth, Mark Ruffalo",
		Writers: "Chris McKenna, Erik Sommers",
		Country: "USA",
		Language: "English",
		Awards: "N/A",
		BoxOffice: "$1.921 billion",
		Runtime: "148 min",
		Plot: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man."
	},
	{
		id: 26,
		Title: "Joker",
		Year: "2006",
		Genre: "Drama, Fantasy",
		Poster: "https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
		imdbRating: "5.0",
		Director: "Jon Favreau",
		Actors: "Mark Ruffalo, Chris Hemsworth, Chris Evans",
		Writers: "Todd Phillips, Scott Silver",
		Country: "USA",
		Language: "English",
		Awards: "2 Oscars",
		BoxOffice: "$1.074 billion",
		Runtime: "122 min",
		Plot: "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker."
	},
	{
		id: 27,
		Title: "Django Unchained",
		Year: "2007",
		Genre: "Thriller, Sci-Fi",
		Poster: "https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_.jpg",
		imdbRating: "7.9",
		Director: "Jon Favreau",
		Actors: "Mark Ruffalo, Chris Evans, Scarlett Johansson",
		Writers: "Quentin Tarantino",
		Country: "USA",
		Language: "English, German, French",
		Awards: "2 Oscars",
		BoxOffice: "$425.4 million",
		Runtime: "165 min",
		Plot: "With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation owner in Mississippi."
	},
	{
		id: 28,
		Title: "The Wolf of Wall Street",
		Year: "2008",
		Genre: "Action, Fantasy",
		Poster: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_.jpg",
		imdbRating: "6.8",
		Director: "Joss Whedon",
		Actors: "Robert Downey Jr., Chris Evans, Mark Ruffalo",
		Writers: "Terence Winter, Jordan Belfort",
		Country: "USA",
		Language: "English",
		Awards: "5 Oscar nominations",
		BoxOffice: "$392 million",
		Runtime: "180 min",
		Plot: "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government."
	},
	{
		id: 29,
		Title: "Shutter Island",
		Year: "2009",
		Genre: "Action, Fantasy",
		Poster: "https://m.media-amazon.com/images/M/MV5BYzhiNDkyNzktNTZmYS00ZTBkLTk2MDAtM2U0YjU1MzgxZjgzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
		imdbRating: "7.1",
		Director: "Anthony Russo",
		Actors: "Scarlett Johansson, Mark Ruffalo, Chris Hemsworth",
		Writers: "Laeta Kalogridis, Dennis Lehane",
		Country: "USA",
		Language: "English, German",
		Awards: "N/A",
		BoxOffice: "$294.8 million",
		Runtime: "138 min",
		Plot: "In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane."
	},
	{
		id: 30,
		Title: "Whiplash",
		Year: "2010",
		Genre: "Adventure, Fantasy",
		Poster: "https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
		imdbRating: "6.3",
		Director: "Joss Whedon",
		Actors: "Mark Ruffalo, Robert Downey Jr., Chris Evans",
		Writers: "Damien Chazelle",
		Country: "USA",
		Language: "English",
		Awards: "3 Oscars",
		BoxOffice: "$49 million",
		Runtime: "106 min",
		Plot: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential."
	},
];

module.exports = movies;
